### ISSUE TITLE
Month names issue for the custom CultureInfo in the `BitDatePicker` component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitplatform#2073]
In the `Jalali BitDatePicker` section, the style of some month's names is not correct.

![Screenshot 2022-05-23 201300](https://user-images.githubusercontent.com/46419023/169857023-0545e332-6559-4174-a527-3063cc5cb609.png)

And, I have a question here, is it ok to use Persian sentence, when all words here are in finglish?

**Comment by msynk** [comment]
Thank you for founding and submitting this issue. about the question you've asked:

Since the month names are coming from the custom CultureInfo object, it's not an issue for the component itself:

![image](https://user-images.githubusercontent.com/6169846/169967706-35891d15-27d3-411a-b8f2-8f574dee6b2a.png)
