### ISSUE TITLE
Replace `Gmail` with `SendGrid` to send signup emails in the `TodoTemplate` project

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#2097]
Replace `Gmail` with `SendGrid` to send signup emails in the `TodoTemplate` project

**Comment by mohabbati** [comment]
The SendGrid account was created, and all settings have been done as follows:
- DNS verification
- Sender configuration
- SMTP configuration

We need to change the value of Azure KeyVault keys for email settings. And, DONE.
The SMTP information will send privately to @ysmoradi.

**Comment by msynk** [comment]
@ysmoradi 
do we need to change anything in the IAC project that needs a separate issue?

**Comment by ysmoradi** [comment]
There won't be any PR for this. We just tested our todo template with SendGrid and now we're sure other people are able to use this fantastic service with current SMTP implementation that we've

**Comment by ysmoradi** [comment]
We just tested the to-do template with SendGrid and it works fine. If you sign-up in the todo template in https://app-service-td-test.azurewebsites.net/ it will send you an email confirmation link using no-reply@bitplatform.dev
But we could not use the sendgrid branding feature, which reduces the chance of being detected as spam because it uses a subdomain of `bitplatform.dev` for all links, and our current HTTPS certificate does not support subdomains.
We're trying to use `bitplatform.dev` for our cdn endpoint (instead of azure app service endpoint) and we then use another certificate that supports subdomains and then we can give it a try again using sendgrid branding config enabled.
For now, I close this issue
