### ISSUE TITLE
BitMessageBar component UI issues

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2539]
BitMessageBar component UI issues.
Test on the new Blazor project
- Truncated Parameter does not work, when the text is long, the page gets scrolls and the text doesn't ellipsis or wrap
- In the Component demo page it's ok (with site CSS)
`<BitMessageBar MessageBarType="@BitMessageBarType.Success" IsMultiline="false" Truncated="true">`

**Comment by MeysamBahadori** [comment]
How about it?
```
<div style="width:100%">
    <BitMessageBar MessageBarType="@BitMessageBarType.Success" IsMultiline="false" Truncated="true">
          large text...
    </BitMessageBar> 
</div>
```
vs 
```
 <div style="width:100%">
     <span>large text ...</span>
 </div>
 
```

**Comment by msynk** [comment]
The BitMessageBar tries to keep the content in 1 line and then truncate it, in order to have a nice posture.
it's accomplished by `white-space: nowrap;`
in this situation, the BitMessageBar width needs to be set clearly. you can't compare it with the simple example you posted above. your sample does not render the component in 1 line clearly. it'll break it into multiple lines.
