### ISSUE TITLE
VisibleItemsCount in BitCarousel

### ISSUE THREAD

**Issue by mhrastegary77** [bitfoundation/bitplatform#2823]
### Summary
When we set the VisibleItemsCount equal or close to the item counts the last item(the one that goes away) gets like hidden before swiping complete.

# Sample Video

https://user-images.githubusercontent.com/42671084/182010597-f96bdeb1-e932-4e2a-81bf-93bdad8238f9.mp4

**Comment by msynk** [comment]
if I get the issue currently, it's by design to allow the coming slides to slide in the correct place.
it actually prioritizes the new/coming slides over the old/leaving ones.

**Comment by mhrastegary77** [comment]
I'll give you a video of it ASAP.

**Comment by mhrastegary77** [comment]
just added a video, might wanna check it out. @msynk

**Comment by msynk** [comment]
thanks a lot. yeah, I guessed it right. it's by design.
as you can see the element is going to be removed from one end and be shown on the other end of the scrolling element. since it can't appear at both ends, it will be removed from the leaving side and only shown on the entering side of the carousel.
