### ISSUE TITLE
Suggestion: Components that mimics MAUI XAML controls

### ISSUE THREAD

**Issue by timahrentlov** [bitfoundation/bitplatform#2964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If you're a mobil XF/MAUI developer that wants to get started with Blazor, you need to learn HTML/CSS. Coming from XAML with all it's Grids, Stacklayouts, HorizontalOption properties, Margin properties, and the like, you now need to think in terms of Div's that adorned with the proper CSS to give you the same thing.

But what if there's was a component kit that resembled the XAML you're used to? What if there was components with parameters that sort of felt the same way, and worked the same way? Just to get you started?

I don't think there's anything like this out there, where it's all about data grids, charts and what's not.    

### Describe the solution you'd like

Components with parameters that makes XF/Maui developers feel at home, and be immediately productive. Layouts, CollectionViews, etc.

**Comment by msynk** [comment]
@timahrentlov thanks for submitting this issue.
this is an exciting idea to have XAML counterpart components in the blazor area too, but in the web world, it's a bad practice to have layout elements since generating the layout is a CSS job and not an HTML task. HTML is there only to generate the structure and configuring the layout is not a structuring task.
Although the reasoning behind your request is rational and acceptable, I'll discuss this request with our team and will be back with the result.

**Comment by mhrastegary77** [comment]
Strongly love to see this one day happens :)

**Comment by timahrentlov** [comment]
In effect, what I am suggesting is a componentized design framework. Something that is for Blazor what [TailwindCss](https://tailwindcss.com/) is for HTML. It's not about doing away with CSS. It's about harnessing it. Abstracting it. It's all about productivity. And just as with Tailwindcss, the developer would be to pull out their own CSS at every line, and bitfoundation would be make money on something similar to [TailwindUI](https://tailwindui.com/). 

Theres currently no such thing out there. There are many components doing some fancy stuff, that's only used once in a blue moon. Theres no component design systems doing the day-to-day bread'n'butter stuff, that's need to truly boost productivity.

Of course, it does not have to be linked to MAUI XAML controls. It could also be Flutter widgets. But putting it close to a known UI design system, would accelerate the adoption IMO.

**Comment by msynk** [comment]
This is what I talked about, in web world it's a bad practice to have a component that applies a layout. for example a `StackLayout` component like in XAML. It's not a good practice to have a component that enables a specific layout, you could have a library consisting a set of predefined layout as CSS classes, but not a component like `<StackLayout>...</StackLayout>`.

Although, We could try to develop such components because of reasons you described, but it's generally a bad practice in web.

**Comment by msynk** [comment]
Anyway, the good new is that we are investigating adding a new project to the bit platform to develop these bad practiced but somehow required components under and Extended program. this project's name is discussed to be something like `Bit.BlazorUI.Extended` or `Bit.BlazorUI.Extensions` or `Bit.BlazorUI.Extras` or ... .

**Comment by mhrastegary77** [comment]
Wow! Awesome :))))))))))

**Comment by msynk** [comment]
not planned yet
