### ISSUE TITLE
Navigate on the footer is not properly 

### ISSUE THREAD

**Issue by ajafarip** [bitfoundation/bitplatform#3159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on the main website when you click on [TodoTemplate](https://bitplatform.dev/project-templates/todo-template/getting-started)
 [AdminPanel](https://bitplatform.dev/project-templates/admin-panel-template/getting-started) they redirect to 404 page.

### Expected Behavior

they should be navigated to https://bitplatform.dev/todo-template/getting-started instead of https://bitplatform.dev/project-templates/todo-template/getting-started

**Comment by msynk** [comment]
@ajafarip 
First of all, thank you for submitting this issue. since you didn't mention the exact place that has this issue, I assume you are talking about the footer links.
The bitplatform website is under heavy development and a lot of things will change in the near future. although we are aware of these issues, we will resolve them with non-direct solutions in the next version.
I'm closing this issue since we are already resolving it.
