### ISSUE TITLE
Failed Unit Test of the `BitRating` component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitplatform#431]
The issue is on "BitRatingShouldRespectClickIndex" test

**Comment by msynk** [comment]
It appears that the issue is somewhere in the bUnit framework. as I investigated the issue, apparently the component works well on the consumer side (for example in Component.razor), but in the test, there is a wired behaviour of the bUnit itself which is making the 2-way bound parameter to be reset multiple times.

**Comment by zoha-shobbar** [comment]
this issue is handled in pull request #833  and the part of the bUnit issue get comment until it gets solved

**Comment by msynk** [comment]
since it is somehow resolved now, I'm closing this issue.
