### ISSUE TITLE
How can I use plugins in BitChart?

### ISSUE THREAD

**Issue by afshinalizadeh** [bitfoundation/bitplatform#7138]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm trying to create a chart with BitChart and I've found the plugin parameters in `_config.Options.Plugins` and `_config.Plugins`. However, I'm having trouble using them.

For instance, how can I use the following inline plugin?

```javascript
const centerBedImage = {
  id: "centerImage",
  afterDraw(chart: any, args: any, pluginOptions: any) {
    const { ctx, data } = chart;
    ctx.save();
    var image = new Image();
    image.src = bed;
    const imageSize = 30;
    const { top, left, width, height } = chart.chartArea;
    const x = left + width / 2 - imageSize / 2;
    const y = top + height / 2 - imageSize / 2;
    ctx.drawImage(image, x, y, imageSize, imageSize);
    ctx.restore();
  },
};
```
Also, how can I use plugin libraries like `chartjs-plugin-datalabels`?

**Comment by msynk** [comment]
@afshinalizadeh Thanks for contacting us.
As explained in the summary documentation of the `Plugins` property of the `BitChartConfigBase` class, in order to register a plugin for BitChart you need to do it through global plugin registration of the `chartjs` as explained here:

https://www.chartjs.org/docs/2.9.4/developers/plugins.html#global-plugins
